# Generated by Django 3.0.5 on 2020-04-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='other',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='pdf',
        ),
    ]
