# Generated by Django 3.0.5 on 2020-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200405_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='docs',
        ),
        migrations.AddField(
            model_name='materials',
            name='files',
            field=models.FileField(default=1, upload_to='materials/Files/'),
            preserve_default=False,
        ),
    ]
