# Generated by Django 3.0.5 on 2020-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20200405_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='files',
            field=models.FileField(upload_to='Materials'),
        ),
    ]
